### ISSUE TITLE
OAuth2AuthorizationServer中的configure方法报错？

### ISSUE THREAD

**Issue by travels-of-little-stone-pond** [nivance/spring-security-oauth2#1]
@Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints)
            throws Exception {
        endpoints.tokenStore(tokenStore())
                .authenticationManager(authenticationManager)
                // 这里一直报错是什么原因呢？
                .userDetailsService(myUserService)
        ;
    }

**Comment by nivance** [comment]
> @override
> public void configure(AuthorizationServerEndpointsConfigurer endpoints)
> throws Exception {
> endpoints.tokenStore(tokenStore())
> .authenticationManager(authenticationManager)
> // 这里一直报错是什么原因呢？
> .userDetailsService(myUserService)
> ;
> }

我确认了一下，没有错，pom.xml没改吧
